# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9f5fa6746a5013237097b274c8c818354ffe29ce4813b9dd9e10da0d7a5e5c611fae0d2ef84ec9332186a00679252e143057513c5e798afa3c86389b2112d906

test:
  secret_key_base: 09a0f0db0dea091190415c41f80e7c7a151d6d9c46bee10a7ccc9ff910f1f8c6449ff1c0f7a84de0fe936b949d2a10659cd8b271d43ab8a74fd6e480f8fb1ebf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
